/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import AccesoADatos.AlumnoData;
import javax.swing.table.DefaultTableModel;
import AccesoADatos.InscripcionData;
import AccesoADatos.MateriaData;
import entidades.Alumno;
import entidades.Inscripcion;
import entidades.Materia;
import java.util.ArrayList;
import java.util.List;
import javax.swing.RowSorter;
import javax.swing.RowSorter.SortKey;
import javax.swing.SortOrder;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Lucas E. Sayago
 */
public class FormulariosDeInscripcionView extends javax.swing.JInternalFrame {

    private final InscripcionData iData = new InscripcionData();
    private final AlumnoData aData = new AlumnoData();
    private final MateriaData mData = new MateriaData();
    private DefaultTableModel modelo;
    private ArrayList<Materia> materias = new ArrayList<>();
    private ArrayList<Alumno> alumnos = new ArrayList<>();

    /**
     * Creates new form FormulariosDeTareasView
     */
    public FormulariosDeInscripcionView() {
        this.modelo = new DefaultTableModel();
        initComponents();
        armarCabecera();
        armarCombox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCAlumnos = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jRBmateriasInscriptas = new javax.swing.JRadioButton();
        jRBmateriasnoinscriptas = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablaDeMaterias = new javax.swing.JTable();
        jBInscribir = new javax.swing.JButton();
        jBAnularInscripcion = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Formulario de Inscripcion");

        jLabel2.setText("Seleccione un alumno:");

        jCAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCAlumnosActionPerformed(evt);
            }
        });

        jLabel3.setText("Listado de Materias");

        jRBmateriasInscriptas.setText("Materias Inscriptas");
        jRBmateriasInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBmateriasInscriptasActionPerformed(evt);
            }
        });

        jRBmateriasnoinscriptas.setText("Materias no Inscriptas");
        jRBmateriasnoinscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBmateriasnoinscriptasActionPerformed(evt);
            }
        });

        jTablaDeMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTablaDeMaterias);

        jBInscribir.setText("Inscribir");
        jBInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInscribirActionPerformed(evt);
            }
        });

        jBAnularInscripcion.setText("Anular Inscripcion");
        jBAnularInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAnularInscripcionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jRBmateriasInscriptas)
                                    .addGap(34, 34, 34)
                                    .addComponent(jRBmateriasnoinscriptas))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(jCAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(94, 94, 94))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jBInscribir)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBAnularInscripcion)
                            .addGap(58, 58, 58)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(205, 205, 205))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(158, 158, 158))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBmateriasInscriptas)
                    .addComponent(jRBmateriasnoinscriptas))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBInscribir)
                    .addComponent(jBAnularInscripcion))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRBmateriasnoinscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBmateriasnoinscriptasActionPerformed
        limpiarTabla();

        // corregimos los botones
        jBInscribir.setEnabled(true);
        jBAnularInscripcion.setEnabled(false);

        jRBmateriasInscriptas.setSelected(false);

        Alumno alum = (Alumno) jCAlumnos.getSelectedItem();
        materias = (ArrayList<Materia>) iData.obtenerMateriasNoCursadas(alum.getIdAlumno());

        llenarTabla(materias);

    }//GEN-LAST:event_jRBmateriasnoinscriptasActionPerformed

    private void jCAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCAlumnosActionPerformed
    }//GEN-LAST:event_jCAlumnosActionPerformed

    private void jRBmateriasInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBmateriasInscriptasActionPerformed
        // corregimos los botones
        jBInscribir.setEnabled(false);
        jBAnularInscripcion.setEnabled(true);

        jRBmateriasnoinscriptas.setSelected(false);
        limpiarTabla();
        Alumno alum = (Alumno) jCAlumnos.getSelectedItem();
        materias = (ArrayList<Materia>) iData.obtenerMateriasCursadas(alum.getIdAlumno());

        llenarTabla(materias);
    }//GEN-LAST:event_jRBmateriasInscriptasActionPerformed

    private void jBInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInscribirActionPerformed
// guardamos la info de la primer fila que es id

        int seleccionDeFila = jTablaDeMaterias.getSelectedRow();

        if (seleccionDeFila > -1) {

            int idMateria = Integer.parseInt(modelo.getValueAt(seleccionDeFila, 0).toString());

            Materia materia = mData.buscarMateria(idMateria);

            Inscripcion insc = new Inscripcion((Alumno) jCAlumnos.getSelectedItem(), materia, 0);

            iData.guardarInscripcion(insc);

            // vuleve a tocar el boton para actualizar
            jRBmateriasnoinscriptasActionPerformed(evt);
        }
    }//GEN-LAST:event_jBInscribirActionPerformed

    private void jBAnularInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAnularInscripcionActionPerformed

        int seleccionDeFila = jTablaDeMaterias.getSelectedRow();

        if (seleccionDeFila > -1) {

            int idMateria = Integer.parseInt(modelo.getValueAt(seleccionDeFila, 0).toString());

            Alumno alum = (Alumno) jCAlumnos.getSelectedItem();

            iData.borrarInscripcionesMateriaAlumno(alum.getIdAlumno(), idMateria);

            // vuleve a tocar el boton para actualizar
            jRBmateriasInscriptasActionPerformed(evt);
        }


    }//GEN-LAST:event_jBAnularInscripcionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAnularInscripcion;
    private javax.swing.JButton jBInscribir;
    private javax.swing.JComboBox<Alumno> jCAlumnos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRBmateriasInscriptas;
    private javax.swing.JRadioButton jRBmateriasnoinscriptas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablaDeMaterias;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void armarCabecera() {

        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Año");

        jTablaDeMaterias.setModel(modelo);

    }

    private void armarCombox() {
        /*
        try {
            //miConexion conexion = new miConexion("jdbc:mariadb://localhost:3306/universidadulp", "root", "");

            //conexion a la db 
            Connection conexion = DriverManager.getConnection("jdbc:mariadb://localhost:3306/universidadulp", "root", "");
            String sql = " SELECT  dni, apellido,nombre FROM alumno WHERE 1";

            PreparedStatement ps = conexion.prepareStatement(sql);

            ResultSet resultado = ps.executeQuery();
            Class.forName("org.mariadb.jdbc.Driver");

            while (resultado.next()) {

                jCAlumnos.addItem(resultado.getInt("dni") + ", " + resultado.getString("apellido") + ", " + resultado.getString("nombre"));

            }

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, " error ");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, " error ");
        }

         */

        alumnos = (ArrayList<Alumno>) aData.listarAlumnos();

        for (Alumno alumn : alumnos) {
            jCAlumnos.addItem(alumn);

        }
    }

    private void limpiarTabla() {

        modelo.setRowCount(0);
    }

    private void llenarTabla(ArrayList<Materia> materias) {

        // Limpiar la tabla (opcional, depende de tu lógica)
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }

        // Llenar la tabla
        for (Materia xmateria : materias) {
            Object[] rowData = {xmateria.getIdMateria(), xmateria.getNombre(), xmateria.getAnioMateria()};
            modelo.addRow(rowData);
        }

        // Habilitar el ordenamiento automático
        jTablaDeMaterias.setAutoCreateRowSorter(true);

        // Establecer un TableRowSorter (no es estrictamente necesario si solo deseas ordenamiento básico)
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(modelo);
        jTablaDeMaterias.setRowSorter(sorter);

        // Si deseas un ordenamiento específico por defecto (por ejemplo, por idMateria en orden ascendente)
        List<RowSorter.SortKey> sortKeys = new ArrayList<>();
        sortKeys.add(new RowSorter.SortKey(0, SortOrder.ASCENDING));
        sorter.setSortKeys(sortKeys);

        modelo = new DefaultTableModel() {
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                switch (columnIndex) {
                    case 0:
                        return Integer.class;
                    case 1:
                    case 2:
                        return String.class;
                    default:
                        return super.getColumnClass(columnIndex);
                }
            }
        };

    }
}


