/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import AccesoADatos.InscripcionData;
import AccesoADatos.MateriaData;
import entidades.Alumno;
import entidades.Materia;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author niqog
 */
public class ListadoAlumnosPorMateriasView extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo = new DefaultTableModel();
    private MateriaData mdata = new MateriaData();
    private InscripcionData idata = new InscripcionData();

    /**
     * Creates new form ListadoAlumnosPorMaterias
     */
    public ListadoAlumnosPorMateriasView() {
        initComponents();
        // modelo = (DefaultTableModel) jTable1.getModel();
        armarCabecera();
        armarComboBox();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCmateria = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBOrdenAsc = new javax.swing.JButton();
        jBOrdenDesc = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Listado de Alumnos por Materia");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Seleccione una materia :");

        jCmateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmateriaActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jBOrdenAsc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotitos/a-z 28 size.png"))); // NOI18N
        jBOrdenAsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOrdenAscActionPerformed(evt);
            }
        });

        jBOrdenDesc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotitos/z-a 28 size.png"))); // NOI18N
        jBOrdenDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOrdenDescActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Orden");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(13, 13, 13)
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(jCmateria, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jBOrdenAsc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jBOrdenDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(125, 125, 125))))
                .addContainerGap(105, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(265, 265, 265))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCmateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBOrdenAsc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBOrdenDesc))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCmateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmateriaActionPerformed
        // borramos las filas
        modelo.setRowCount(0);

        //llenamos el array con todos los alumnos de esa materia
        Materia materia = (Materia) jCmateria.getSelectedItem();
        ArrayList<Alumno> listadAlumuno = (ArrayList) idata.obtenerAlumnosXMateria(materia.getIdMateria());

        //llenar la tabla con los datos de el array creado
        for (Alumno alumno : listadAlumuno) {
            Object[] rowData = {alumno.getIdAlumno(), alumno.getDni(), alumno.getApellido(),alumno.getNombre() };
            modelo.addRow(rowData);
        }
    }//GEN-LAST:event_jCmateriaActionPerformed

    private void jBOrdenAscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOrdenAscActionPerformed

        // borramos las filas
        modelo.setRowCount(0);

        //llenamos el array con todos los alumnos de esa materia
        Materia materia = (Materia) jCmateria.getSelectedItem();
        ArrayList<Alumno> listadAlumuno = (ArrayList) idata.obtenerAlumnosXMateriaOrdenAsc(materia.getIdMateria());

        //llenar la tabla con los datos de el array creado
        for (Alumno alumno : listadAlumuno) {
            Object[] rowData = {alumno.getIdAlumno(), alumno.getDni(), alumno.getApellido(),alumno.getNombre() };
            modelo.addRow(rowData);
        }
    }//GEN-LAST:event_jBOrdenAscActionPerformed

    private void jBOrdenDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOrdenDescActionPerformed

        // borramos las filas
        modelo.setRowCount(0);

        //llenamos el array con todos los alumnos de esa materia
        Materia materia = (Materia) jCmateria.getSelectedItem();
        ArrayList<Alumno> listadAlumuno = (ArrayList) idata.obtenerAlumnosXMateriaOrdenDesc(materia.getIdMateria());

        //llenar la tabla con los datos de el array creado
        for (Alumno alumno : listadAlumuno) {
            Object[] rowData = {alumno.getIdAlumno(), alumno.getDni(), alumno.getApellido(),alumno.getNombre() };
            modelo.addRow(rowData);
        }

    }//GEN-LAST:event_jBOrdenDescActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBOrdenAsc;
    private javax.swing.JButton jBOrdenDesc;
    private javax.swing.JComboBox<Materia> jCmateria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void armarCabecera() {

        modelo.addColumn("ID");
        modelo.addColumn("DNI");
        modelo.addColumn("Apellido");
        modelo.addColumn("Nombre");

        jTable1.setModel(modelo);

    }

    private void armarComboBox() {

        MateriaData md = new MateriaData();
        ArrayList<Materia> materias = (ArrayList) md.listarMaterias();

        for (Materia materia : materias) {
            jCmateria.addItem(materia);
        }

    }

}
